services:
  web:
    restart: unless-stopped
    command: "npm run start"
  metabase:
    image: metabase/metabase
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file: .env
    volumes:
      - metabase:/metabase-data
    environment:
      MB_DB_DBNAME: metabase
      MB_DB_FILE: /metabase-data/metabase.db
      MB_DB_TYPE: mysql
      MB_DB_HOST: ${DB_HOST:-mysql}
      MB_DB_USER: ${DB_USER:-root}
      MB_DB_PASS: ${DB_PASSWORD}
      MB_DB_PORT: ${DB_PORT:-3306}
