version: "3.9"
services:
  web:
    image: node:lts-alpine
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
    command: npm install
  mysql:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "GraphTL"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: null
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    tmpfs: /sessions
    ports:
      - 8080:80
    env_file: .env
    environment:
      PMA_HOST: ${DB_HOST:-mysql}
      PMA_USER: ${DB_USER:-root}
      PMA_PASSWORD: ${DB_PASSWORD}
volumes:
  mysql:
  metabase:
